[package]
name = "retro"
version = "0.1.0"
authors = ["Sean Toner <placeoftheway@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8"
rand = "0.8"
num-traits = "0.2"

[dependencies.serde]
features = ["derive"]
version = "1.0"
