#!/bin/zsh

# githook to run before pushing 
# - Check if there are updated crates
# - cargo build
# - cargo test
# - cargo audit 

echo "################################"
echo "Checking if there are updated crates..."
cargo update --dry-run


echo "################################"
echo "Running audit check..."
cargo audit
