name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@nextest
    - name: Prerequisites
      run: sudo apt-get install clang pkg-config libx11-dev libasound2-dev libudev-dev mesa-vulkan-drivers
    - name: Clippy check
      run: cargo clippy --all-targets --all-features -- -Dwarnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo nextest run
    - name: Audit
      run: cargo audit
