name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Prerequisites
      run: sudo apt-get install clang pkg-config libx11-dev libasound2-dev libudev-dev mesa-vulkan-drivers
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
